PREFIX dfd: <https://devprivops.com/dfd/>
PREFIX dpia: <https://devprivops.com/dpia/>

# NOTE: requires DFD definition

SELECT ?data ?dest
WHERE {
    dpia:ROOT dpia:personal_data ?data .
    ?data dpia:destinataries ?dest .
    FILTER NOT EXISTS {
        {
            dfd:ROOT dfd:external_entities ?ent .
            ?ent dfd:categories ?dest .
        } UNION {
            dfd:ROOT dfd:external_entities ?dest .
        }
    }
}

