PREFIX ex: <https://example.com/>

# NOTE: requires DFD

SELECT ?purpose
WHERE {
    {
        ex:ROOT ex:personal_data/ex:purposes ?purpose .
    } UNION {
        ex:ROOT ex:personal_data_processing_whitelist ?purpose .
    } UNION {
        ex:ROOT ex:personal_data_processing_that_requires_DPIA ?purpose .
    } 

    FILTER NOT EXISTS {
        ex:ROOT ex:processings ?processing .
        ?processing ex:purposes ?purpose .
    }
}