PREFIX ex: <https://example.com/>

# NOTE: requires DFD

SELECT ?ext_ent
WHERE {
    ex:ROOT ex:personal_data/ex:destinataries ?ext_ent .
    FILTER NOT EXISTS {
        ex:ROOT ex:external_entities ?ext_ent .
    }
}

