PREFIX dfd: <https://devprivops.com/dfd/>
PREFIX dpia: <https://devprivops.com/dpia/>

# NOTE: requires DFD

SELECT ?ext_ent
WHERE {
    dpia:ROOT dpia:personal_data/dpia:destinataries ?ext_ent .

    FILTER NOT EXISTS {
        {
            dfd:ROOT dfd:external_entities ?ext_ent .
        } UNION {
            dfd:ROOT dfd:external_entities ?ent .
            ?ent dfd:categories ?ext_ent .
        }
    }
}

