PREFIX dpia: <https://devprivops.com/dpia/>

# Based on Article 5,6

SELECT *
WHERE {
    dpia:ROOT dpia:processings ?processing . 

    # Art 5 1 a | is this the right place to have this info?
    {
        BIND("lawful fair transparent" AS ?reason)
        # ?processing dpia:lawful ?lawful .
        # ?processing dpia:fair ?fair .
        # ?processing dpia:transparent ?transparent .
        FILTER NOT EXISTS {
            ?processing dpia:lawful true . # Defined by Art 6 1
            ?processing dpia:fair true .
            ?processing dpia:transparent true .
        }
    }
    
    # Art 5 1 b
    UNION { 
        BIND("specific explicit legitimate" AS ?reason)
        FILTER NOT EXISTS {
            ?processing dpia:specific true .
            ?processing dpia:explicit true .
            ?processing dpia:legitimate true .
        }
    }

    # Art 5 1 c
#     UNION {
#         BIND("adequate relevant limited" AS ?reason)
#          
#             ?processing dpia:purposes ?p .
#             ?p dpia:adequate true .
#             ?p dpia:relevant true .
#             ?p dpia:limited true .
# #         FILTER NOT EXISTS {
# #             ?processing dpia:purposes ?p .
# #             ?p dpia:adequate true .
# #             ?p dpia:relevant true .
# #             ?p dpia:limited true .
# #         }
# #         {
# #              ?p dpia:adequate false .
# #         } UNION {
# #              ?p dpia:relevant false .
# #         } UNION {
# #              ?p dpia:limited false .
# #         }
#     }

    # Art 5 1 e ?????????????

    # Art 5 1 f ? to the responsability of security regulations?
}