PREFIX ex: <https://example.com/>

# Based on Article 5,6

SELECT *
WHERE {
    ex:ROOT ex:purposes ?purpose . 

    # Art 5 1 a | is this the right place to have this info?
    FILTER NOT EXISTS {
        ?purpose ex:lawful "true" . # Defined by Art 6 1
        ?purpose ex:fair "true" .
        ?purpose ex:transparent "true" .
    }

    # Art 5 1 b
    FILTER NOT EXISTS {
        ?purpose ex:specific "true" .
        ?purpose ex:explicit "true" .
        ?purpose ex:legitimate "true" .
    }

    # Art 5 1 c
    FILTER NOT EXISTS {
        ?purpose ex:adequate "true" .
        ?purpose ex:relevant "true" .
        ?purpose ex:limited "true" .
    }

    # Art 5 1 e ?????????????

    # Art 5 1 f ? to the responsability of security regulations?
}