PREFIX ex: <https://example.com/>

# Based on Article 5,6

SELECT *
WHERE {
    ex:ROOT ex:processings ?processing . 

    # Art 5 1 a | is this the right place to have this info?
    FILTER NOT EXISTS {
        ?processing ex:lawful true . # Defined by Art 6 1
        ?processing ex:fair true .
        ?processing ex:transparent true .
    }

    # Art 5 1 b
    FILTER NOT EXISTS {
        ?processing ex:specific true .
        ?processing ex:explicit true .
        ?processing ex:legitimate true .
    }

    # Art 5 1 c
    ?processing ex:purposes ?p .
    FILTER NOT EXISTS {
        ?p ex:adequate true .
        ?p ex:relevant true .
        ?p ex:limited true .
    }

    # Art 5 1 e ?????????????

    # Art 5 1 f ? to the responsability of security regulations?
}