PREFIX ex: <https://example.com/>

# NOTE: requires a DFD

SELECT ?purpose
WHERE {
    ex:ROOT ex:processes/ex:purposes ?purpose .

    FILTER NOT EXISTS {
        ex:ROOT ex:processings/ex:purposes ?purpose .
    } 
}