PREFIX dfd: <https://devprivops.com/dfd/>
PREFIX dpia: <https://devprivops.com/dpia/>

SELECT ?dsId ?dtId
WHERE {
    dfd:ROOT dfd:data_stores ?dsId .
    ?dsId dfd:data_stored ?dataStored . 
    ?dataStored dfd:type ?dtId .

    ?dsId dfd:environment "browser" .
    ?dtId dfd:categories dpia:authenticated_only . # TODO: detect data obtained while authenticated

    FILTER NOT EXISTS {
        ?dataStored dfd:storage_period: "session" .
    }
}
