PREFIX dfd: <https://devprivops.com/dfd/>

SELECT ?dsId ?dtId
WHERE {
    dfd:ROOT dfd:data_stores ?dsId .
    ?dsId dfd:data_stored ?dt .
	
	?dt dfd:type ?dtId .
	?dt dfd:location "browser" .
    
	?dtId dfd:categories dfd:sensitive .
}
