PREFIX dfd: <https://devprivops.com/dfd/>

SELECT ?dtId
WHERE {
    {
        ?_ dfd:consumes ?dtId
    } UNION {
        ?_ dfd:produces ?dtId
    } UNION {
        ?_ dfd:type ?dtId
    } UNION {
        ?_ dfd:data ?dtId
    } UNION {
        ?_ dfd:aggregates ?dtId
    }
    FILTER NOT EXISTS {
        dfd:ROOT dfd:data_types ?dtId
    }
}