PREFIX dfd: <https://devprivops.com/dfd/>

# Could be useless because insuficient_rights_over_data exists

SELECT ?dfId
WHERE {
    {
        ?_ dfd:create ?dfId
    } UNION {
        ?_ dfd:read ?dfId
    } UNION {
        ?_ dfd:update ?dfId
    } UNION {
        ?_ dfd:delete ?dfId
    }
    FILTER NOT EXISTS {
        dfd:ROOT dfd:data_flows ?dfId 
    }
}

