PREFIX dfd: <https://devprivops.com/dfd/>
PREFIX dpia: <https://devprivops.com/dpia/>

SELECT ?eId
WHERE {
    {
        ?_ dpia:vital_interest ?eId .
    } UNION {
        ?_ dpia:legitimate_interest ?eId .
    } 

    FILTER NOT EXISTS {
        {
            dfd:ROOT dfd:external_entities ?eId .
        } UNION {
            dfd:ROOT dfd:external_entities/dfd:categories ?eId .
        }
    }
}
