PREFIX ex: <https://example.com/>

SELECT ?dtId
WHERE {
    {
        ?_ ex:consumes ?dtId
    } UNION {
        ?_ ex:produces ?dtId
    } UNION {
        ?_ ex:type ?dtId
    } UNION {
        ?_ ex:data ?dtId
    } UNION {
        ?_ ex:aggregates ?dtId
    }
    FILTER NOT EXISTS {
        ex:ROOT ex:data_types ?dtId
    }
}