PREFIX dfd: <https://devprivops.com/dfd/>

SELECT ?df ?matchedPredicate ?serviceId
WHERE {
  	{
    	?df dfd:from ?serviceId .
        BIND("from" AS ?matchedPredicate)
  	} UNION {
        ?df dfd:to ?serviceId .
        BIND("to" AS ?matchedPredicate)
    }
  	MINUS {
        dfd:ROOT dfd:external_entities|dfd:processes|dfd:data_stores ?serviceId .
    }
}
