PREFIX ex: <https://example.com/>

SELECT ?df ?matchedPredicate ?serviceId
WHERE {
  	{
    	?df ex:from ?serviceId .
        BIND("from" AS ?matchedPredicate)
  	} UNION {
        ?df ex:to ?serviceId .
        BIND("to" AS ?matchedPredicate)
    }
  	MINUS {
        ex:ROOT ex:external_entities|ex:processes|ex:data_stores ?serviceId .
    }
}
