PREFIX dfd: <https://devprivops.com/dfd/>
PREFIX dpia: <https://devprivops.com/dpia/>

INSERT {
    dpia:ROOT dpia:visitor_spied_by_owner ?data .  
} WHERE {
    dfd:Visitor dfd:produces ?data .
    dfd:Home_Owner dfd:consumes ?data .
}
