PREFIX dfd: <https://devprivops.com/dfd/>

SELECT ?subject ?time
WHERE {
    ?subject dfd:validity|dfd:periodicity ?time .
    FILTER NOT EXISTS {
        FILTER(
            REGEX(?time, "^[0-9]+(s|sec|secs|second|seconds|m|min|mins|minute|minutes|h|hr|hrs|hour|hours|d|day|days|w|week|weeks|month|months|y|year|years)$") ||
            ?time = "eternal"
        )
    }
}