PREFIX ex: <https://example.com/>

# Useless since it is enforced by the schema
SELECT ?ds ?dtName ?missingPredicate
WHERE {
  ?ds ex:data_stored ?dt .
  ?dt ex:type ?dtName .

  OPTIONAL {
    {
      ?dt ex:create ?dfId .
      BIND("create" as ?missingPredicate)
    } UNION {
      ?dt ex:read ?dfId .
      BIND("read" as ?missingPredicate)
    } UNION {
      ?dt ex:update ?dfId .
      BIND("update" as ?missingPredicate)
    } UNION {
      ?dt ex:delete ?dfId .
      BIND("delete" as ?missingPredicate)
    }
  }

  FILTER NOT EXISTS {
    ex:ROOT ex:data_flows ?df .
  }
}