PREFIX dfd: <https://devprivops.com/dfd/>

# Useless since it is enforced by the schema
SELECT ?ds ?dtName ?missingPredicate
WHERE {
  ?ds dfd:data_stored ?dt .
  ?dt dfd:type ?dtName .

  OPTIONAL {
    {
      ?dt dfd:create ?dfId .
      BIND("create" as ?missingPredicate)
    } UNION {
      ?dt dfd:read ?dfId .
      BIND("read" as ?missingPredicate)
    } UNION {
      ?dt dfd:update ?dfId .
      BIND("update" as ?missingPredicate)
    } UNION {
      ?dt dfd:delete ?dfId .
      BIND("delete" as ?missingPredicate)
    }
  }

  FILTER NOT EXISTS {
    dfd:ROOT dfd:data_flows ?df .
  }
}