PREFIX dfd: <https://devprivops.com/dfd/>
PREFIX dpia: <https://devprivops.com/dpia/>

SELECT * WHERE {
    dpia:AuthenticatedUser dfd:consumes dfd:Document .
    dpia:AuthenticatedUser dfd:consumes dfd:PrivDocument .
    BIND("FOUND" as ?success)
}
