PREFIX ex: <https://example.com>

SELECT ?eId
WHERE {
    {
        ?_ ex:vital_interest ?eId
    } UNION {
        ?_ ex:legitimate_interest ?eId
    } 
#    UNION {
#        ?_ ex:from ?eId
#    } UNION {
#        ?_ ex:to ?eId
#    }
    FILTER NOT EXISTS {
        ex:ROOT ex:external_entities ?e .
        ?e ex:id ?eId
#        ?e ex:location ?_
#        ?e ex:categories ?_
#        ?e ex:age ?_
#        ?e ex:produces_public_information ?_
    }
}
